version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: sclab-presto-connectorproxy
    ports:
      - '9180:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  sclab-presto-connector:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: sclab-presto-connector
    ports:
      - '3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  sclab-client-data:
    driver: local
