version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '9180:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  sclab-presto-connector:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: sclab-presto-connector
    ports:
      - '3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  trino:
    ports:
      - "8080:8080"
    image: "trinodb/trino:latest"
    volumes:
      - ./presto/etc:/usr/lib/trino/etc:ro
      - ./presto/catalog:/etc/trino/catalog

networks:
  backend:
    driver: bridge

volumes:
  sclab-client-data:
    driver: local
