version: '3.7'

services:
  trino:
    ports:
      - "8080:8080"
    image: "trinodb/trino:latest"
    volumes:
      - ./config:/etc/trino
      - ./plugin:/usr/lib/trino/plugin
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
networks:
  backend:
    driver: bridge

volumes:
  trino-data:
    driver: local
